language: dart
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

dart:
  - dev
  # Stable is temporarily disabled since this requires dart 2.0 and above.
  # - stable

matrix:
  allow_failures:
    - dart: dev

before_install:
  - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
  - export CHROMEDRIVER_ARGS=--no-sandbox
  - /usr/bin/chromium-browser --version

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$PWD
  - ./tool/travis-setup.sh

script: 
  - ./tool/travis.sh
