targets:
  $default:
    sources: ["lib/**"]
    builders:
      built_value_generator|built_value:
        enabled: true
      pageloader|pageloader:
        enabled: false
  _tests:
    sources: ["test/**"]
    builders:
      built_value_generator|built_value:
        enabled: false
      pageloader|pageloader:
        enabled: true

builders:
  pageloader:
    import: "package:pageloader/builder.dart"
    builder_factories: ["pageloaderBuilder"]
    build_extensions: {".dart": [".pageloader.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
